# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_remove_entry_n_pingbacks'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='n_pingbacks',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
