# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 07:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_entry_n_pingbacks'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeBlog',
            fields=[
                ('blog_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myblog.Blog')),
                ('theme', models.CharField(max_length=200)),
            ],
            bases=('myblog.blog',),
        ),
    ]
