# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0005_auto_20171104_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('data', models.IntegerField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publishers',
        ),
        migrations.RemoveField(
            model_name='store',
            name='books',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
