# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 06:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0007_article_book_bookreview_piece'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreview',
            name='name',
            field=models.CharField(default=datetime.datetime(2017, 11, 10, 6, 29, 53, 69602, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
