# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 02:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_remove_question_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 31, 2, 51, 33, 255282, tzinfo=utc), verbose_name='date published'),
        ),
    ]
